// Auto-generated image map
// Maps original images to optimized WebP versions
// Generated: 2026-01-04T17:01:12.352Z

export const imageMap = {
  "/bakershelf.png": "/optimized/bakershelf.webp",
  "/baker_shelf/Chocolate Crinkles.png": "/optimized/baker_shelf/Chocolate Crinkles.webp",
  "/baker_shelf/Chocolate Nemesis.png": "/optimized/baker_shelf/Chocolate Nemesis.webp",
  "/baker_shelf/Hazelnut Cookies.png": "/optimized/baker_shelf/Hazelnut Cookies.webp",
  "/baker_shelf/Pear Breton.png": "/optimized/baker_shelf/Pear Breton.webp",
  "/Bites.jpg": "/optimized/Bites.webp",
  "/Bitters.png": "/optimized/Bitters.webp",
  "/bread/Almond-Criossant.png": "/optimized/bread/Almond-Criossant.webp",
  "/bread/Cinnamon-Lemon-Roll.png": "/optimized/bread/Cinnamon-Lemon-Roll.webp",
  "/bread/Classic Challah.jpg": "/optimized/bread/Classic Challah.webp",
  "/bread/country-loaf.png": "/optimized/bread/country-loaf.webp",
  "/bread/germanbaguette.jpg": "/optimized/bread/germanbaguette.webp",
  "/bread/japanesemilkbread.jpg": "/optimized/bread/japanesemilkbread.webp",
  "/bread/Olive.png": "/optimized/bread/Olive.webp",
  "/bread/Plain-Sourdough.png": "/optimized/bread/Plain-Sourdough.webp",
  "/bread/Rye.png": "/optimized/bread/Rye.webp",
  "/bread/Sourdough.png": "/optimized/bread/Sourdough.webp",
  "/bread/Sun-dried.png": "/optimized/bread/Sun-dried.webp",
  "/bread/tartine.png": "/optimized/bread/tartine.webp",
  "/cake/Black Forest.png": "/optimized/cake/Black Forest.webp",
  "/cake/ChocoHazelnut.png": "/optimized/cake/ChocoHazelnut.webp",
  "/cake/CoconutDream.png": "/optimized/cake/CoconutDream.webp",
  "/cake/StrawberryCheeseCake.png": "/optimized/cake/StrawberryCheeseCake.webp",
  "/cake/Tiramisu.png": "/optimized/cake/Tiramisu.webp",
  "/cherry.png": "/optimized/cherry.webp",
  "/Delicatessen.png": "/optimized/Delicatessen.webp",
  "/desserts1.jpg": "/optimized/desserts1.webp",
  "/Fraisier.png": "/optimized/Fraisier.webp",
  "/Fraisier1.png": "/optimized/Fraisier1.webp",
  "/Lumiere/12 One Biters.png": "/optimized/Lumiere/12 One Biters.webp",
  "/Lumiere/4 One Biters.png": "/optimized/Lumiere/4 One Biters.webp",
  "/Lumiere/Breads/Multigrain Sourdough.png": "/optimized/Lumiere/Breads/Multigrain Sourdough.webp",
  "/Lumiere/Breads/Olive Sourdough.png": "/optimized/Lumiere/Breads/Olive Sourdough.webp",
  "/Lumiere/Breads/Plain Sourdough.png": "/optimized/Lumiere/Breads/Plain Sourdough.webp",
  "/Lumiere/Breads/Rye Sourdough.png": "/optimized/Lumiere/Breads/Rye Sourdough.webp",
  "/Lumiere/Breads/Sun-dried tomatoes & Garlic Sourdough.png": "/optimized/Lumiere/Breads/Sun-dried tomatoes & Garlic Sourdough.webp",
  "/Lumiere/Cake/Blackcurrant Queen Cake.png": "/optimized/Lumiere/Cake/Blackcurrant Queen Cake.webp",
  "/Lumiere/Cake/ChocoHazelnut Cake.png": "/optimized/Lumiere/Cake/ChocoHazelnut Cake.webp",
  "/Lumiere/Cake/Cleopatre Cake.png": "/optimized/Lumiere/Cake/Cleopatre Cake.webp",
  "/Lumiere/Cake/Coconut Dream Cake.png": "/optimized/Lumiere/Cake/Coconut Dream Cake.webp",
  "/Lumiere/Cake/Lemon Pistachio Meringue Cake.png": "/optimized/Lumiere/Cake/Lemon Pistachio Meringue Cake.webp",
  "/Lumiere/Cake/Raspberry Pistachio Cake.png": "/optimized/Lumiere/Cake/Raspberry Pistachio Cake.webp",
  "/Lumiere/Cake/Strawberry Cheesecake.png": "/optimized/Lumiere/Cake/Strawberry Cheesecake.webp",
  "/Lumiere/Cake/Tiramisu Cake.png": "/optimized/Lumiere/Cake/Tiramisu Cake.webp",
  "/Lumiere/Pastry/Almond Criossant.png": "/optimized/Lumiere/Pastry/Almond Criossant.webp",
  "/Lumiere/Pastry/Cheese Danish.png": "/optimized/Lumiere/Pastry/Cheese Danish.webp",
  "/Lumiere/Pastry/Chocolatin.png": "/optimized/Lumiere/Pastry/Chocolatin.webp",
  "/Lumiere/Pastry/Cinnamon Lemon Roll.png": "/optimized/Lumiere/Pastry/Cinnamon Lemon Roll.webp",
  "/Lumiere/Pastry/DIplomat Criossant.png": "/optimized/Lumiere/Pastry/DIplomat Criossant.webp",
  "/Lumiere/Pastry/Double Chocolate Criossant.png": "/optimized/Lumiere/Pastry/Double Chocolate Criossant.webp",
  "/Lumiere/Pastry/Fruit Danish.png": "/optimized/Lumiere/Pastry/Fruit Danish.webp",
  "/Lumiere/Pastry/Pear Danish.png": "/optimized/Lumiere/Pastry/Pear Danish.webp",
  "/Lumiere/Pastry/Raspberry Cheesecake Criossant.png": "/optimized/Lumiere/Pastry/Raspberry Cheesecake Criossant.webp",
  "/Lumiere/Pastry/Salted Caramel Criossant.png": "/optimized/Lumiere/Pastry/Salted Caramel Criossant.webp",
  "/Lumiere/Personal Desserts/Black Forest.png": "/optimized/Lumiere/Personal Desserts/Black Forest.webp",
  "/Lumiere/Personal Desserts/Blackcurrant Queen.png": "/optimized/Lumiere/Personal Desserts/Blackcurrant Queen.webp",
  "/Lumiere/Personal Desserts/Cleopatra.png": "/optimized/Lumiere/Personal Desserts/Cleopatra.webp",
  "/Lumiere/Personal Desserts/Coconut Dream.png": "/optimized/Lumiere/Personal Desserts/Coconut Dream.webp",
  "/Lumiere/Personal Desserts/Cream & Crumb.png": "/optimized/Lumiere/Personal Desserts/Cream & Crumb.webp",
  "/Lumiere/Personal Desserts/Creme Berry Tart.png": "/optimized/Lumiere/Personal Desserts/Creme Berry Tart.webp",
  "/Lumiere/Personal Desserts/Daisy.png": "/optimized/Lumiere/Personal Desserts/Daisy.webp",
  "/Lumiere/Personal Desserts/Dubai Chocolate.png": "/optimized/Lumiere/Personal Desserts/Dubai Chocolate.webp",
  "/Lumiere/Personal Desserts/Lemon Pistachio Meringue.png": "/optimized/Lumiere/Personal Desserts/Lemon Pistachio Meringue.webp",
  "/Lumiere/Personal Desserts/Peaches & Cream.png": "/optimized/Lumiere/Personal Desserts/Peaches & Cream.webp",
  "/Lumiere/Personal Desserts/Personal Heart.png": "/optimized/Lumiere/Personal Desserts/Personal Heart.webp",
  "/Lumiere/Personal Desserts/Raspberry Pistachio Tart.png": "/optimized/Lumiere/Personal Desserts/Raspberry Pistachio Tart.webp",
  "/Lumiere/Personal Desserts/Rings of Paris.png": "/optimized/Lumiere/Personal Desserts/Rings of Paris.webp",
  "/Lumiere/Personal Desserts/Strawberry Cheesecake Tart.png": "/optimized/Lumiere/Personal Desserts/Strawberry Cheesecake Tart.webp",
  "/Lumiere/Personal Desserts/Sweet Pleasure.png": "/optimized/Lumiere/Personal Desserts/Sweet Pleasure.webp",
  "/Lumiere/Personal Desserts/Tiramichoux.png": "/optimized/Lumiere/Personal Desserts/Tiramichoux.webp",
  "/Lumiere Cheesecake.png": "/optimized/Lumiere Cheesecake.webp",
  "/Lumiere Cheesecake2.png": "/optimized/Lumiere Cheesecake2.webp",
  "/lumiere.png": "/optimized/lumiere.webp",
  "/Lumière.png": "/optimized/Lumière.webp",
  "/Noisette Noir.png": "/optimized/Noisette Noir.webp",
  "/one_bite/12.png": "/optimized/one_bite/12.webp",
  "/one_bite/4.png": "/optimized/one_bite/4.webp",
  "/pastry/croisants.jpg": "/optimized/pastry/croisants.webp",
  "/pastry/pastry.png": "/optimized/pastry/pastry.webp",
  "/personal_dessert/Cream & Crumb.png": "/optimized/personal_dessert/Cream & Crumb.webp",
  "/personal_dessert/Creme Berry Tart.png": "/optimized/personal_dessert/Creme Berry Tart.webp",
  "/personal_dessert/Heart.png": "/optimized/personal_dessert/Heart.webp",
  "/personal_dessert/Lemon Pistachio Meringue.png": "/optimized/personal_dessert/Lemon Pistachio Meringue.webp",
  "/personal_dessert/Paris Brest.png": "/optimized/personal_dessert/Paris Brest.webp",
  "/personal_dessert/Peaches & Cream.png": "/optimized/personal_dessert/Peaches & Cream.webp",
  "/personal_dessert/Rings of Paris.png": "/optimized/personal_dessert/Rings of Paris.webp",
  "/personal_dessert/Strawberry Cheesecake Tart.png": "/optimized/personal_dessert/Strawberry Cheesecake Tart.webp",
  "/personal_dessert/Strawberry.png": "/optimized/personal_dessert/Strawberry.webp",
  "/personal_dessert/Tiramichoux.png": "/optimized/personal_dessert/Tiramichoux.webp",
  "/Petit Fours (Box of 4)2.png": "/optimized/Petit Fours (Box of 4)2.webp",
  "/plain.png": "/optimized/plain.webp",
  "/Sweet.png": "/optimized/Sweet.webp",
  "/sweet1.png": "/optimized/sweet1.webp",
  "/Tiramichoux2.png": "/optimized/Tiramichoux2.webp",
  "/tiramisuhome.png": "/optimized/tiramisuhome.webp",
  "/Uber-Eats-logo.png": "/optimized/Uber-Eats-logo.webp"
};

/**
 * Get optimized image path
 * @param {string} originalPath - Original image path (e.g., "/bread/Sourdough.png")
 * @returns {string} - Optimized WebP path (e.g., "/optimized/bread/Sourdough.webp")
 */
export function getOptimizedImage(originalPath) {
  return imageMap[originalPath] || originalPath;
}
