// Image map for optimized WebP versions
// Maps original images to optimized WebP versions

export const imageMap = {
  "/images/bakery-shelf/600_0472.jpg": "/optimized/images/bakery-shelf/600_0472.webp",
  "/images/bakery-shelf/Baklava Tart.png": "/optimized/images/bakery-shelf/Baklava Tart.webp",
  "/images/bakery-shelf/Chocolate Crincle Cookie.jpg": "/optimized/images/bakery-shelf/Chocolate Crincle Cookie.webp",
  "/images/bakery-shelf/Chocolate Nemesis.png": "/optimized/images/bakery-shelf/Chocolate Nemesis.webp",
  "/images/bakery-shelf/Hazelnut Cookies.jpg": "/optimized/images/bakery-shelf/Hazelnut Cookies.webp",
  "/images/bakery-shelf/Hazelnut Cookies.png": "/optimized/images/bakery-shelf/Hazelnut Cookies.webp",
  "/images/bakery-shelf/Z61_2324.jpg": "/optimized/images/bakery-shelf/Z61_2324.webp",
  "/images/breads/Classic Challah.jpg": "/optimized/images/breads/Classic Challah.webp",
  "/images/breads/French Baguette.jpg": "/optimized/images/breads/French Baguette.webp",
  "/images/breads/japanese milk bread.jpg": "/optimized/images/breads/japanese milk bread.webp",
  "/images/breads/Olive Sourdough.png": "/optimized/images/breads/Olive Sourdough.webp",
  "/images/breads/Plain Sourdough.png": "/optimized/images/breads/Plain Sourdough.webp",
  "/images/breads/Rye & Wallnut Sourdough.png": "/optimized/images/breads/Rye & Wallnut Sourdough.webp",
  "/images/breads/Tomatoes & Garlic Sourdough.png": "/optimized/images/breads/Tomatoes & Garlic Sourdough.webp",
  "/images/breads/Whole Wheat & Seeds Sourdough.png": "/optimized/images/breads/Whole Wheat & Seeds Sourdough.webp",
  "/images/cakes/Blackcurrant Queen Cake.png": "/optimized/images/cakes/Blackcurrant Queen Cake.webp",
  "/images/cakes/ChocoHazelnut Cake.png": "/optimized/images/cakes/ChocoHazelnut Cake.webp",
  "/images/cakes/Cleopatre Cake.png": "/optimized/images/cakes/Cleopatre Cake.webp",
  "/images/cakes/Coconut Dream Cake.png": "/optimized/images/cakes/Coconut Dream Cake.webp",
  "/images/cakes/Lemon Pistachio Meringue Cake.png": "/optimized/images/cakes/Lemon Pistachio Meringue Cake.webp",
  "/images/cakes/Raspberry Pistachio Cake.png": "/optimized/images/cakes/Raspberry Pistachio Cake.webp",
  "/images/cakes/Strawberry Cheesecake.png": "/optimized/images/cakes/Strawberry Cheesecake.webp",
  "/images/cakes/Tiramisu Cake.png": "/optimized/images/cakes/Tiramisu Cake.webp",
  "/images/one-biters/One Biters 12pc.png": "/optimized/images/one-biters/One Biters 12pc.webp",
  "/images/one-biters/One Biters 4pc.png": "/optimized/images/one-biters/One Biters 4pc.webp",
  "/images/pastries/Almond Criossant.png": "/optimized/images/pastries/Almond Criossant.webp",
  "/images/pastries/Butter Criossant.png": "/optimized/images/pastries/Butter Criossant.webp",
  "/images/pastries/Chocolatine.png": "/optimized/images/pastries/Chocolatine.webp",
  "/images/pastries/Cinnamon Roll.png": "/optimized/images/pastries/Cinnamon Roll.webp",
  "/images/pastries/Creme DIplomat Criossant.png": "/optimized/images/pastries/Creme DIplomat Criossant.webp",
  "/images/pastries/Double Milk Chocolate Criossant.png": "/optimized/images/pastries/Double Milk Chocolate Criossant.webp",
  "/images/pastries/Fruit Danish.png": "/optimized/images/pastries/Fruit Danish.webp",
  "/images/pastries/Raspberry Cheesecake Criossant.png": "/optimized/images/pastries/Raspberry Cheesecake Criossant.webp",
  "/images/pastries/Salted Caramel Criossant.png": "/optimized/images/pastries/Salted Caramel Criossant.webp",
  "/images/pastries/Sweet Cheese Danish.png": "/optimized/images/pastries/Sweet Cheese Danish.webp",
  "/images/personal-desserts/Black Forest Sliced.jpg": "/optimized/images/personal-desserts/Black Forest Sliced.webp",
  "/images/personal-desserts/Black Forest.png": "/optimized/images/personal-desserts/Black Forest.webp",
  "/images/personal-desserts/Blackcurrant Queen Sliced.jpg": "/optimized/images/personal-desserts/Blackcurrant Queen Sliced.webp",
  "/images/personal-desserts/Blackcurrant Queen.png": "/optimized/images/personal-desserts/Blackcurrant Queen.webp",
  "/images/personal-desserts/Cleopatra Sliced.jpg": "/optimized/images/personal-desserts/Cleopatra Sliced.webp",
  "/images/personal-desserts/Cleopatra.png": "/optimized/images/personal-desserts/Cleopatra.webp",
  "/images/personal-desserts/Coconut Dream Sliced.jpg": "/optimized/images/personal-desserts/Coconut Dream Sliced.webp",
  "/images/personal-desserts/Coconut Dream.png": "/optimized/images/personal-desserts/Coconut Dream.webp",
  "/images/personal-desserts/Cream & Crumb.png": "/optimized/images/personal-desserts/Cream & Crumb.webp",
  "/images/personal-desserts/Creme Berry Tart (Blueberry).png": "/optimized/images/personal-desserts/Creme Berry Tart (Blueberry).webp",
  "/images/personal-desserts/Creme Berry Tart (Rasberry).png": "/optimized/images/personal-desserts/Creme Berry Tart (Rasberry).webp",
  "/images/personal-desserts/Creme Berry Tart Sliced.jpg": "/optimized/images/personal-desserts/Creme Berry Tart Sliced.webp",
  "/images/personal-desserts/Daisy Sliced.jpg": "/optimized/images/personal-desserts/Daisy Sliced.webp",
  "/images/personal-desserts/Daisy.png": "/optimized/images/personal-desserts/Daisy.webp",
  "/images/personal-desserts/Duabi Chocolate Sliced.jpg": "/optimized/images/personal-desserts/Duabi Chocolate Sliced.webp",
  "/images/personal-desserts/Dubai Chocolate.png": "/optimized/images/personal-desserts/Dubai Chocolate.webp",
  "/images/personal-desserts/Lemon Pistachio Meringue Sliced.jpg": "/optimized/images/personal-desserts/Lemon Pistachio Meringue Sliced.webp",
  "/images/personal-desserts/Lemon Pistachio Meringue.png": "/optimized/images/personal-desserts/Lemon Pistachio Meringue.webp",
  "/images/personal-desserts/Peaches & Cream.png": "/optimized/images/personal-desserts/Peaches & Cream.webp",
  "/images/personal-desserts/Peaches and Cream Sliced.jpg": "/optimized/images/personal-desserts/Peaches and Cream Sliced.webp",
  "/images/personal-desserts/Personal Heart Sliced.jpg": "/optimized/images/personal-desserts/Personal Heart Sliced.webp",
  "/images/personal-desserts/Personal Heart.jpg": "/optimized/images/personal-desserts/Personal Heart.webp",
  "/images/personal-desserts/Personal Heart.png": "/optimized/images/personal-desserts/Personal Heart.webp",
  "/images/personal-desserts/Raspberry Pistachio Tart Sliced.jpg": "/optimized/images/personal-desserts/Raspberry Pistachio Tart Sliced.webp",
  "/images/personal-desserts/Raspberry Pistachio Tart.png": "/optimized/images/personal-desserts/Raspberry Pistachio Tart.webp",
  "/images/personal-desserts/Rings of Paris Sliced.jpg": "/optimized/images/personal-desserts/Rings of Paris Sliced.webp",
  "/images/personal-desserts/Rings of Paris.png": "/optimized/images/personal-desserts/Rings of Paris.webp",
  "/images/personal-desserts/Strawberry Cheesecake Sliced.jpg": "/optimized/images/personal-desserts/Strawberry Cheesecake Sliced.webp",
  "/images/personal-desserts/Strawberry Cheesecake Tart.png": "/optimized/images/personal-desserts/Strawberry Cheesecake Tart.webp",
  "/images/personal-desserts/Sweet Pleasure.png": "/optimized/images/personal-desserts/Sweet Pleasure.webp",
  "/images/personal-desserts/Tiramichoux Sliced.jpg": "/optimized/images/personal-desserts/Tiramichoux Sliced.webp",
  "/images/personal-desserts/Tiramichoux.png": "/optimized/images/personal-desserts/Tiramichoux.webp",
  "/images/web-design/Logo 1.jpg": "/optimized/images/web-design/Logo 1.webp",
  "/images/web-design/Logo 2.jpg": "/optimized/images/web-design/Logo 2.webp",
  "/images/web-design/lumiere Logo.png": "/optimized/images/web-design/lumiere Logo.webp",
  "/images/web-design/Lumière inside Photo.png": "/optimized/images/web-design/Lumière inside Photo.webp",
  "/images/web-design/Uber-Eats-logo.png": "/optimized/images/web-design/Uber-Eats-logo.webp",
  "/Black Forest.png": "/optimized/Black Forest.webp",
  "/Lumière.png": "/optimized/Lumière.webp",
};

/**
 * Get optimized image path
 * @param {string} originalPath - Original image path (e.g., "/bread/Sourdough.png")
 * @returns {string} - Optimized WebP path (e.g., "/optimized/bread/Sourdough.webp")
 */
export function getOptimizedImage(originalPath) {
  return imageMap[originalPath] || originalPath;
}
