// src/products/productSamples.js
import slugify from "slugify";

const raw = [
  //One Biters
  {
    name: "One Biter Assortment Box (4 pcs)",
    price: 16,
    imageUrl: "/Lumiere/4 One Biters.png",
    category: "onebite",
  },
  {
    name: "One Biter Assortment Box (12 pcs)",
    price: 48,
    imageUrl: "/Lumiere/12 One Biters.png",
    category: "onebite",
  },
  // CAKES (from /Lumiere/Cake)
  {
    name: "Blackcurrant Queen Cake",
    price: 50.0,
    imageUrl: "/Lumiere/Cake/Blackcurrant Queen Cake.png",
    category: "cakes",
    description: "Blackcurrant Diplomat, Blackcurrant Mousse, Hazelnut Crunch. Gluten Free, Dairy Free.",
  },
  {
    name: "ChocoHazelnut Cake",
    price: 49.0,
    imageUrl: "/Lumiere/Cake/ChocoHazelnut Cake.png",
    category: "cakes",
    description: "Milk Chocolate Ganache, Milk Chocolate Mousse, Hazelnut Crunch.",
  },
  {
    name: "Cleopatre Cake",
    price: 48.0,
    imageUrl: "/Lumiere/Cake/Cleopatre Cake.png",
    category: "cakes",
    description: "Blackcurrant Compote, Blackcurrant Mousse, Hazelnut Crunch.",
  },
  {
    name: "Coconut Dream Cake",
    price: 44.0,
    imageUrl: "/Lumiere/Cake/Coconut Dream Cake.png",
    category: "cakes",
    description: "Coconut Diplomat, Coconut Mousse, Toasted Coconut.",
  },
  {
    name: "Lemon Pistachio Meringue Cake",
    price: 50.0,
    imageUrl: "/Lumiere/Cake/Lemon Pistachio Meringue Cake.png",
    category: "cakes",
    description: "Pistachio Almond Cream, Raspberry Mousse, Almond Short Dough. Gluten Free.",
  },
  {
    name: "Raspberry Pistachio Cake",
    price: 49.0,
    imageUrl: "/Lumiere/Cake/Raspberry Pistachio Cake.png",
    category: "cakes",
    description: "Pistachio Almond Cream, Raspberry Mousse, Almond Short Dough. Gluten Free.",
  },
  {
    name: "Strawberry Cheesecake",
    price: 46.0,
    imageUrl: "/Lumiere/Cake/Strawberry Cheesecake.png",
    category: "cakes",
    description: "Light Cheesecake, Strawberry Mousse, Buttery Crumb. Gluten Free.",
  },
  {
    name: "Tiramisu Cake",
    price: 50.0,
    imageUrl: "/Lumiere/Cake/Tiramisu Cake.png",
    category: "cakes",
    description: "Tiramisu Mousse, Soft Chocolate Sponge, Coffee Syrup, Cappuccino Chantilly.",
  },
  {
    name: "Cream & Crumb Cake",
    price: 44.0,
    imageUrl: "/Lumiere/Cake/Cream & Crumb Cake.png",
    category: "cakes",
    description: "Light No-Bake Cheesecake, Buttery Crumble, Graham Cracker Crust.",
  },

  // PERSONAL DESSERTS (from /Lumiere/Personal Desserts)
  {
    name: "Sweet Pleasure",
    price: 11.5,
    imageUrl: "/Lumiere/Personal Desserts/Sweet Pleasure.png",
    category: "personal-desserts",
    description: "Dark Chocolate Mousse, Chocolate Ganache, Chocolate Insert.",
  },
  {
    name: "Tiramichoux",
    price: 10.5,
    imageUrl: "/Lumiere/Personal Desserts/Tiramichoux.png",
    category: "personal-desserts",
    description: "Cocoa Craquelin Choux Pastry, Sabayon Mascarpone Cream, Espresso Biscotti Savoiardi, Cappuccino Chantilly.",
  },
  {
    name: "Raspberry Pistachio Tart",
    price: 10.0,
    imageUrl: "/Lumiere/Personal Desserts/Raspberry Pistachio Tart.png",
    category: "personal-desserts",
    description: "Pistachio Almond Cream, Raspberry Mousse, Almond Short Dough. Gluten Free.",
  },
  {
    name: "Black Forest",
    price: 10.5,
    imageUrl: "/Lumiere/Personal Desserts/Black Forest.png",
    category: "personal-desserts",
    description: "Chocolate Sponge, Cherry Compote, Kirsch Cream, Chocolate Chantilly.",
  },
  {
    name: "Dubai Chocolate",
    price: 11.5,
    imageUrl: "/Lumiere/Personal Desserts/Dubai Chocolate.png",
    category: "personal-desserts",
    description: "Cocoa Tart Shell, Hazelnut Praliné, Dark Chocolate Ganache, Milk Chocolate Mousse.",
  },
  {
    name: "Rings of Paris",
    price: 11.0,
    imageUrl: "/Lumiere/Personal Desserts/Rings of Paris.png",
    category: "personal-desserts",
    description: "Pistachio Almond Cream, Raspberry Compote, Ruby Chocolate Ganache, Cocoa Tart.",
  },
  {
    name: "Lemon Pistachio Meringue",
    price: 11.5,
    imageUrl: "/Lumiere/Personal Desserts/Lemon Pistachio Meringue.png",
    category: "personal-desserts",
    description: "Pistachio Diplomat, Dairy-Free Lemon Cream, Meringue. Gluten Free.",
  },
  {
    name: "Peaches & Cream",
    price: 11.0,
    imageUrl: "/Lumiere/Personal Desserts/Peaches & Cream.png",
    category: "personal-desserts",
    description: "Passion Fruit Mousse, Coconut Bavaroise, Peach Mousse, Cocoa Tart.",
  },
  {
    name: "Cream & Crumb",
    price: 9.50,
    imageUrl: "/Lumiere/Personal Desserts/Cream & Crumb.png",
    category: "personal-desserts",
    description: "Light No-Bake Cheesecake, Buttery Crumbles, Graham Cracker Crust",
  },
  {
    name: "Blackcurrant Queen",
    price: 11.0,
    imageUrl: "/Lumiere/Personal Desserts/Blackcurrant Queen.png",
    category: "personal-desserts",
    description: "Blackcurrant Compote, Blackcurrant Mousse, Hazelnut Crunch. Gluten Free.",
  },
  {
    name: "Coconut Dream",
    price: 10.5,
    imageUrl: "/Lumiere/Personal Desserts/Coconut Dream.png",
    category: "personal-desserts",
    description: "Coconut Diplomat, Coconut Mousse, Toasted Coconut.",
  },
  {
    name: "Personal Heart",
    price: 10.5,
    imageUrl: "/Lumiere/Personal Desserts/Personal Heart.png",
    category: "personal-desserts",
    description: "Raspberry Rose Mousse , Lychee Insert",
  },
  {
    name: "Strawberry Cheesecake Tart",
    price: 10.0,
    imageUrl: "/Lumiere/Personal Desserts/Strawberry Cheesecake Tart.png",
    category: "personal-desserts",
    description: "Light Cheesecake, Strawberry Mousse, Buttery Crumble, Almond Short Dough",
  },
  {
    name: "Cleopatra",
    price: 11.5,
    imageUrl: "/Lumiere/Personal Desserts/Cleopatra.png",
    category: "personal-desserts",
    description: "Milk Chocolate Ganache, Milk Chocolate Cream, Hazelnut Wafer",
  },
  {
    name: "Creme Berry Tart",
    price: 9,
    imageUrl: "/Lumiere/Personal Desserts/Creme Berry Tart.png",
    category: "personal-desserts",
    description: "Almond Short Crust, Vanilla Crème Pâtissier, Fresh Ontario Berries",
  },
  {
    name: "Daisy",
    price: 11.5,
    imageUrl: "/Lumiere/Personal Desserts/Daisy.png",
    category: "personal-desserts",
    description: "Light Vanilla Mousse, Fresh Berries, Almond Crumble.",
  },

    // 🥐 PASTRIES (from /Lumiere/Pastry)
  {
    name: "Almond Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Almond Criossant.png",
    category: "pastries",
    description: "Flaky croissant filled with almond cream and topped with toasted almonds.",
  },
  {
    name: "Double Milk Chocolate Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Double Chocolate Criossant.png",
    category: "pastries",
    description: "Rich buttery croissant layered with double milk chocolate filling.",
  },
  {
    name: "Butter Croissant",
    price: 4.5,
    imageUrl: "/Lumiere/Pastry/Butter Croissant.png",
    category: "pastries",
    description: "Classic French croissant with a flaky crust and soft buttery interior.",
  },
  {
    name: "Salted Caramel Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Salted Caramel Criossant.png",
    category: "pastries",
    description: "Golden croissant filled with salted caramel and topped with glaze.",
  },
  {
    name: "Raspberry Cheesecake Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Raspberry Cheesecake Criossant.png",
    category: "pastries",
    description: "Filled with raspberry compote and cheesecake cream.",
  },
  {
    name: "Pistachio Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Pistachio Croissant.png",
    category: "pastries",
    description: "Rich pistachio cream inside buttery croissant layers.",
  },
  {
    name: "Creme Diplomat Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/DIplomat Criossant.png",
    category: "pastries",
    description: "Croissant filled with smooth crème diplomat and dusted with icing sugar.",
  },
  {
    name: "Chocolatine",
    price: 5.5,
    imageUrl: "/Lumiere/Pastry/Chocolatin.png",
    category: "pastries",
    description: "Classic chocolate-filled pastry with crisp golden layers.",
  },
  {
    name: "Sweet Cheese Danish",
    price: 5.1,
    imageUrl: "/Lumiere/Pastry/Cheese Danish.png",
    category: "pastries",
    description: "Soft Danish pastry filled with smooth sweet cheese.",
  },
  {
    name: "Cherry Danish",
    price: 5.75,
    imageUrl: "/Lumiere/Pastry/Fruit Danish.png",
    category: "pastries",
    description: "Danish topped with cherry compote and light glaze.",
  },
  {
    name: "Cinnamon Roll",
    price: 5.25,
    imageUrl: "/Lumiere/Pastry/Cinnamon Lemon Roll.png",
    category: "pastries",
    description: "Soft roll with buttery cinnamon sugar filling and icing drizzle.",
  },
  {
    name: "Pecan Salted Caramel Danish",
    price: 6.25,
    imageUrl: "/Lumiere/Pastry/Pecan Salted Caramel Danish.png",
    category: "pastries",
    description: "Sweet Danish pastry topped with pecans and caramel glaze.",
  },
  {
    name: "Coconut Passion Fruit Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Coconut Passion Fruit Croissant.png",
    category: "pastries",
    description: "Tropical combination of coconut cream and passion fruit filling.",
  },
  {
    name: "Chocolate Chip Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Chocolate Chip Croissant.png",
    category: "pastries",
    description: "Buttery croissant with chocolate chips and light sugar glaze.",
  },

  // 🍞 BREADS (from /Lumiere/Breads)
  {
    name: "Wholewheat & Seeds Sourdough",
    price: 7.5,
    imageUrl: "/Lumiere/Breads/Multigrain Sourdough.png",
    category: "bread",
    description: "Hearty sourdough made with a blend of grains and seeds for extra flavor.",
  },
  {
    name: "Olive Sourdough",
    price: 7.5,
    imageUrl: "/Lumiere/Breads/Olive Sourdough.png",
    category: "bread",
    description: "Rustic sourdough loaf enriched with Kalamata olives.",
  },
  {
    name: "Plain Sourdough",
    price: 7.0,
    imageUrl: "/Lumiere/Breads/Plain Sourdough.png",
    category: "bread",
    description: "Classic country-style sourdough with a crispy crust and chewy crumb.",
  },
  {
    name: "Rye & Walnut Sourdough",
    price: 7.0,
    imageUrl: "/Lumiere/Breads/Rye Sourdough.png",
    category: "bread",
    description: "Dense rye loaf with earthy flavor, perfect for sandwiches.",
  },
  {
    name: "Sun-dried Tomatoes & Garlic Sourdough",
    price: 8.5,
    imageUrl: "/Lumiere/Breads/Sun-dried tomatoes & Garlic Sourdough.png",
    category: "bread",
    description: "Savory sourdough loaf packed with sun-dried tomatoes and roasted garlic.",
  },
];

const samples = raw.map((p, i) => ({
  ...p,
  id: String(i + 1),
  slug: slugify(p.name, { lower: true, strict: true }),
}));

export default samples;
