// src/products/productSamples.js
import slugify from "slugify";

const raw = [
  // ═══════════════════════════════════════════════════════════════════════════
  // ONE BITERS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "One Biter Assortment Box (4 pcs)",
    price: 16,
    imageUrl: "/Lumiere/4 One Biters.png",
    category: "onebite",
    description: "A curated selection of four signature one-bite desserts.",
  },
  {
    name: "One Biter Assortment Box (12 pcs)",
    price: 48,
    imageUrl: "/Lumiere/12 One Biters.png",
    category: "onebite",
    description: "A curated selection of twelve signature one-bite desserts.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CAKES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "ChocoHazelnut Cake",
    price: 56.00,
    imageUrl: "/Lumiere/Cake/ChocoHazelnut Cake.png",
    category: "cakes",
    description: "Milk Chocolate Cremeux, Dark Chocolate Mousse, Hazelnut Crunch.",
    allergens: "has Dairy, has Nut, has Gluten",
  },
  {
    name: "Cleopatre Cake",
    price: 56.00,
    imageUrl: "/Lumiere/Cake/Cleopatre Cake.png",
    category: "cakes",
    description: "Milk Chocolate Ganache, Milk Chocolate Cream, Hazelnut Wafer.",
    allergens: "has Hazelnuts, has Dairy, has Gluten",
  },
  {
    name: "Blackcurrant Queen Cake",
    price: 56.00,
    imageUrl: "/Lumiere/Cake/Blackcurrant Queen Cake.png",
    category: "cakes",
    description: "Blackcurrant Compote, Blackcurrant Mousse, Hazelnut Crunch.",
    allergens: "has Dairy, has Nuts, has Gluten, has Eggs",
  },
  {
    name: "Coconut Dream Cake",
    price: 56.00,
    imageUrl: "/Lumiere/Cake/Coconut Dream Cake.png",
    category: "cakes",
    description: "Coconut Dacquoise, Dairy Free Dark Chocolate Mousse, Toasted Coconut Diplomat.",
    allergenFree: "Gluten Free, Dairy Free, Nut Free",
    allergens: "has Eggs",
  },
  {
    name: "Lemon Pistachio Meringue Cake",
    price: 56.00,
    imageUrl: "/Lumiere/Cake/Lemon Pistachio Meringue Cake.png",
    category: "cakes",
    description: "Pistachio Dacquoise, Dairy Free Lemon Cream, Meringue.",
    allergenFree: "Gluten Free, Dairy Free",
    allergens: "has Nuts, has Eggs",
  },
  {
    name: "Raspberry Pistachio Cake",
    price: 50.00,
    imageUrl: "/Lumiere/Cake/Raspberry Pistachio Cake.png",
    category: "cakes",
    description: "Pistachio Almond Cream, Raspberry Mousse, Almond Short Dough, Macaron.",
    allergens: "has Nuts, has Dairy, has Gluten, has Eggs",
  },
  {
    name: "Strawberry Cheesecake",
    price: 50.00,
    imageUrl: "/Lumiere/Cake/Strawberry Cheesecake.png",
    category: "cakes",
    description: "Light Cheesecake, Strawberry Mousse, Buttery Crumble, Almond Short Dough.",
    allergens: "has Dairy, has Eggs, has Nuts, has Gluten",
  },
  {
    name: "Cream & Crumb Cake",
    price: 44.00,
    imageUrl: "/Lumiere/Cake/Cream & Crumb Cake.png",
    category: "cakes",
    description: "Light No-Bake Cheesecake, Buttery Crumbles, Graham Cracker Crust.",
    allergenFree: "Nut Free",
    allergens: "has Dairy, has Honey, has Gluten",
  },
  {
    name: "Chocolate Cream & Crumb Cake",
    price: 44.00,
    imageUrl: "/Lumiere/Cake/Chocolate Cream & Crumb Cake.png",
    category: "cakes",
    description: "Light No-Bake Chocolate Cheesecake, Cocoa Buttery Crumbles, Graham Cracker Crust.",
    allergenFree: "Nut Free",
  },
  {
    name: "Tiramisu Cake",
    price: 50.00,
    imageUrl: "/Lumiere/Cake/Tiramisu Cake.png",
    category: "cakes",
    description: "Tiramisu Mousse, Soft Chocolate Short Dough, Espresso Syrup, Cappuccino Chantilly.",
    allergenFree: "Nut Free",
  },
  {
    name: "Daisy Cake",
    price: 56.00,
    imageUrl: "/Lumiere/Cake/Daisy Cake.png",
    category: "cakes",
    description: "Passion Fruit Mousse, Passion Fruit Compote, Hazelnut Milk Chocolate Ganache, Cocoa Tart.",
    allergens: "has Nuts, has Dairy, has Eggs, has Gluten",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PERSONAL DESSERTS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Tiramichoux",
    price: 9.00,
    imageUrl: "/Lumiere/Personal Desserts/Tiramichoux.png",
    category: "personal-desserts",
    description: "Cocoa Craquelin Choux Pastry, Sabayon Mascarpone Cream, Espresso Biscotti Savoiardi, Cappuccino Chantilly.",
    allergenFree: "Nut Free",
    allergens: "has Dairy, has Gluten, has Eggs, has Alcohol",
  },
  {
    name: "Sweet Pleasure",
    price: 10.50,
    imageUrl: "/Lumiere/Personal Desserts/Sweet Pleasure.png",
    category: "personal-desserts",
    description: "Hazelnut Dacquoise, Hazelnut Crunch, Milk Chocolate Ganache, Milk Chocolate Chantilly.",
    allergenFree: "Gluten Free",
    allergens: "has Nuts, has Dairy, has Eggs",
  },
  {
    name: "Lemon Pistachio Meringue",
    price: 11.50,
    imageUrl: "/Lumiere/Personal Desserts/Lemon Pistachio Meringue.png",
    category: "personal-desserts",
    description: "Pistachio Dacquoise, Dairy Free Lemon Cream, Meringue.",
    allergenFree: "Gluten Free, Dairy Free",
    allergens: "has Nuts, has Eggs",
  },
  {
    name: "Coconut Dream",
    price: 11.50,
    imageUrl: "/Lumiere/Personal Desserts/Coconut Dream.png",
    category: "personal-desserts",
    description: "Coconut Dacquoise, Dairy Free Dark Chocolate Mousse, Toasted Coconut Diplomat.",
    allergenFree: "Gluten Free, Dairy Free, Nut Free",
    allergens: "has Eggs",
  },
  {
    name: "Rings of Paris",
    price: 10.50,
    imageUrl: "/Lumiere/Personal Desserts/Rings of Paris.png",
    category: "personal-desserts",
    description: "Hazelnut Chantilly, Hazelnut Praline, Choux Pastry.",
    allergens: "has Dairy, has Nuts, has Gluten",
  },
  {
    name: "Dubai Chocolate",
    price: 11.50,
    imageUrl: "/Lumiere/Personal Desserts/Dubai Chocolate.png",
    category: "personal-desserts",
    description: "Cocoa Tart Shell, Kataifi Pistachio, Milk Chocolate Ganache, Milk Chocolate Mousse.",
    allergens: "has Nuts, has Dairy, has Gluten, has Eggs",
  },
  {
    name: "Cream & Crumb",
    price: 9.50,
    imageUrl: "/Lumiere/Personal Desserts/Cream & Crumb.png",
    category: "personal-desserts",
    description: "Light No-Bake Cheesecake, Buttery Crumbles, Graham Cracker Crust.",
    allergenFree: "Nut Free",
    allergens: "has Dairy, has Honey, has Gluten",
  },
  {
    name: "Chocolate Cream & Crumb",
    price: 10.00,
    imageUrl: "/Lumiere/Personal Desserts/Chocolate Cream & Crumb.png",
    category: "personal-desserts",
    description: "Light No-Bake Chocolate Cheesecake, Cocoa Buttery Crumbles, Graham Cracker Crust.",
    allergenFree: "Nut Free",
  },
  {
    name: "Daisy",
    price: 11.50,
    imageUrl: "/Lumiere/Personal Desserts/Daisy.png",
    category: "personal-desserts",
    description: "Passion Fruit Mousse, Passion Fruit Compote, Hazelnut Milk Chocolate Ganache, Cocoa Tart.",
    allergens: "has Nuts, has Dairy, has Eggs, has Gluten",
  },
  {
    name: "Peaches & Cream",
    price: 11.50,
    imageUrl: "/Lumiere/Personal Desserts/Peaches & Cream.png",
    category: "personal-desserts",
    description: "Almond Short Dough, Vanilla Mousse, Peach Joconde, Peach Brunoise.",
    allergens: "has Dairy, has Nuts, has Gluten, has Eggs",
  },
  {
    name: "Blackcurrant Queen",
    price: 11.50,
    imageUrl: "/Lumiere/Personal Desserts/Blackcurrant Queen.png",
    category: "personal-desserts",
    description: "Blackcurrant Compote, Blackcurrant Mousse, Hazelnut Crunch.",
    allergens: "has Dairy, has Nuts, has Gluten, has Eggs",
  },
  {
    name: "Strawberry Cheesecake Tart",
    price: 10.50,
    imageUrl: "/Lumiere/Personal Desserts/Strawberry Cheesecake Tart.png",
    category: "personal-desserts",
    description: "Light Cheesecake, Strawberry Mousse, Buttery Crumble, Almond Short Dough.",
    allergens: "has Dairy, has Eggs, has Nuts, has Gluten",
  },
  {
    name: "Raspberry Pistachio Tart",
    price: 10.50,
    imageUrl: "/Lumiere/Personal Desserts/Raspberry Pistachio Tart.png",
    category: "personal-desserts",
    description: "Pistachio Almond Cream, Raspberry Mousse, Almond Short Dough, Macaron.",
    allergens: "has Nuts, has Dairy, has Gluten, has Eggs",
  },
  {
    name: "Cleopatra",
    price: 11.50,
    imageUrl: "/Lumiere/Personal Desserts/Cleopatra.png",
    category: "personal-desserts",
    description: "Milk Chocolate Ganache, Milk Chocolate Cream, Hazelnut Wafer.",
    allergens: "has Nuts, has Dairy, has Gluten, has Eggs",
  },
  {
    name: "Black Forest",
    price: 10.50,
    imageUrl: "/Lumiere/Personal Desserts/Black Forest.png",
    category: "personal-desserts",
    description: "Dark Chocolate Mousse, Cherry Compote, White Chocolate Insert.",
    allergens: "has Dairy, has Nuts, has Gluten, has Eggs",
  },
  {
    name: "Personal Heart",
    price: 10.50,
    imageUrl: "/Lumiere/Personal Desserts/Personal Heart.png",
    category: "personal-desserts",
    description: "Raspberry Rose Mousse, Lychee Insert.",
    allergens: "has Nuts, has Dairy, has Gluten, has Eggs",
  },
  {
    name: "Creme Berry Tart",
    price: 9.00,
    imageUrl: "/Lumiere/Personal Desserts/Creme Berry Tart.png",
    category: "personal-desserts",
    description: "Almond Short Crust, Vanilla Crème Pâtissier, Fresh Ontario Berries.",
    allergens: "has Nuts, has Dairy, has Gluten, has Eggs",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PASTRIES (Puff Pastry) - Removed Pecan Salted Caramel Danish
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Almond Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Almond Criossant.png",
    category: "pastries",
    description: "Flaky croissant filled with almond cream and topped with toasted almonds.",
  },
  {
    name: "Double Milk Chocolate Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Double Chocolate Criossant.png",
    category: "pastries",
    description: "Rich buttery croissant layered with double milk chocolate filling.",
  },
  {
    name: "Butter Croissant",
    price: 4.50,
    imageUrl: "/Lumiere/Pastry/Butter Croissant.png",
    category: "pastries",
    description: "Classic French croissant with a flaky crust and soft buttery interior.",
  },
  {
    name: "Salted Caramel Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Salted Caramel Criossant.png",
    category: "pastries",
    description: "Golden croissant filled with salted caramel and topped with glaze.",
  },
  {
    name: "Raspberry Cheesecake Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Raspberry Cheesecake Criossant.png",
    category: "pastries",
    description: "Filled with raspberry compote and cheesecake cream.",
  },
  {
    name: "Pistachio Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Pistachio Croissant.png",
    category: "pastries",
    description: "Rich pistachio cream inside buttery croissant layers.",
  },
  {
    name: "Creme Diplomat Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/DIplomat Criossant.png",
    category: "pastries",
    description: "Croissant filled with smooth crème diplomat and dusted with icing sugar.",
  },
  {
    name: "Chocolatine",
    price: 5.50,
    imageUrl: "/Lumiere/Pastry/Chocolatin.png",
    category: "pastries",
    description: "Classic chocolate-filled pastry with crisp golden layers.",
  },
  {
    name: "Sweet Cheese Danish",
    price: 5.10,
    imageUrl: "/Lumiere/Pastry/Cheese Danish.png",
    category: "pastries",
    description: "Soft Danish pastry filled with smooth sweet cheese.",
  },
  {
    name: "Cherry Danish",
    price: 5.75,
    imageUrl: "/Lumiere/Pastry/Fruit Danish.png",
    category: "pastries",
    description: "Danish topped with cherry compote and light glaze.",
  },
  {
    name: "Cinnamon Roll",
    price: 5.25,
    imageUrl: "/Lumiere/Pastry/Cinnamon Lemon Roll.png",
    category: "pastries",
    description: "Soft roll with buttery cinnamon sugar filling and icing drizzle.",
  },
  {
    name: "Chocolate Chip Croissant",
    price: 6.85,
    imageUrl: "/Lumiere/Pastry/Chocolate Chip Croissant.png",
    category: "pastries",
    description: "Buttery croissant with chocolate chips and light sugar glaze.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BREADS (Only: Tartine, Rye & Walnuts, Wholewheat & Seeds, Tomato & Garlic, Olives, Japanese Milk Bread)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Tartine",
    price: 7.00,
    imageUrl: "/Lumiere/Breads/Plain Sourdough.png",
    category: "bread",
    description: "Classic country-style sourdough with a crispy crust and chewy crumb.",
  },
  {
    name: "Rye & Walnut Sourdough",
    price: 7.50,
    imageUrl: "/Lumiere/Breads/Rye Sourdough.png",
    category: "bread",
    description: "Dense rye loaf with walnuts, earthy flavor perfect for sandwiches.",
  },
  {
    name: "Wholewheat & Seeds Sourdough",
    price: 7.50,
    imageUrl: "/Lumiere/Breads/Multigrain Sourdough.png",
    category: "bread",
    description: "Hearty sourdough made with whole wheat and a blend of seeds for extra flavor.",
  },
  {
    name: "Tomato & Garlic Sourdough",
    price: 7.50,
    imageUrl: "/Lumiere/Breads/Sun-dried tomatoes & Garlic Sourdough.png",
    category: "bread",
    description: "Savory sourdough loaf packed with sun-dried tomatoes and roasted garlic.",
  },
  {
    name: "Greek Olive Sourdough",
    price: 7.50,
    imageUrl: "/Lumiere/Breads/Olive Sourdough.png",
    category: "bread",
    description: "Rustic sourdough loaf enriched with Kalamata olives.",
  },
  {
    name: "Japanese Milk Bread",
    price: 6.50,
    imageUrl: "/Lumiere/Breads/Japanese Milk Bread.png",
    category: "bread",
    description: "Soft, fluffy, and slightly sweet bread with a pillowy texture.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BAKERY SHELF
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Choco Chip & Hazelnut Cookies",
    price: 9.75,
    imageUrl: "/baker_shelf/Hazelnut Cookies.png",
    category: "bakery-shelf",
    description: "Buttery cookies studded with chocolate chips and toasted hazelnuts.",
    allergens: "has Nuts, has Gluten, has Eggs, has Dairy",
  },
  {
    name: "Oatmeal Cookies",
    price: 9.75,
    imageUrl: "/baker_shelf/Oatmeal Cookies.png",
    category: "bakery-shelf",
    description: "Classic oatmeal cookies with a chewy texture.",
    allergenFree: "Nut Free",
    allergens: "has Gluten, has Eggs, has Dairy",
  },
  {
    name: "Black Sesame Choco Chip Cookies",
    price: 9.75,
    imageUrl: "/baker_shelf/Black Sesame Cookies.png",
    category: "bakery-shelf",
    description: "Unique cookies with black sesame and chocolate chips.",
    allergenFree: "Nut Free",
    allergens: "has Gluten, has Eggs, has Dairy",
  },
  {
    name: "Halva Cookies",
    price: 9.75,
    imageUrl: "/baker_shelf/Halva Cookies.png",
    category: "bakery-shelf",
    description: "Sweet cookies made with traditional halva.",
    allergenFree: "Nut Free",
    allergens: "has Gluten, has Eggs, has Dairy",
  },
  {
    name: "Baklava Tart",
    price: 25.00,
    imageUrl: "/images/bakery-shelf/Baklava Tart.png",
    category: "bakery-shelf",
    description: "Traditional baklava-inspired tart with layers of phyllo, nuts, and honey.",
  },
  {
    name: "Chocolate Nemesis",
    price: 25.00,
    imageUrl: "/baker_shelf/Chocolate Nemesis.png",
    category: "bakery-shelf",
    description: "Rich, dense flourless chocolate cake with an intense chocolate flavor.",
  },
  {
    name: "Meringues",
    price: 6.75,
    imageUrl: "/baker_shelf/Meringues.png",
    category: "bakery-shelf",
    description: "Light and crispy meringue cookies.",
  },
  {
    name: "Lumiere Marshmallows",
    price: 10.50,
    imageUrl: "/baker_shelf/Marshmallows.png",
    category: "bakery-shelf",
    description: "Handcrafted artisan marshmallows.",
    allergenFree: "Nut Free, Dairy Free, Gluten Free",
  },
  {
    name: "Hazelnut Dacquoise Square",
    price: 12.00,
    imageUrl: "/baker_shelf/Hazelnut Dacquoise.png",
    category: "bakery-shelf",
    description: "Layers of hazelnut meringue with buttercream.",
  },
  {
    name: "Biscotti",
    price: 9.75,
    imageUrl: "/baker_shelf/Biscotti.png",
    category: "bakery-shelf",
    description: "Traditional Italian twice-baked cookies, perfect with coffee.",
  },
  {
    name: "Crinkle Cookie",
    price: 3.50,
    imageUrl: "/baker_shelf/Chocolate Crinkles.png",
    category: "bakery-shelf",
    description: "Fudgy chocolate cookies coated in powdered sugar with a crackled top.",
    allergenFree: "Nut Free, Dairy Free",
    allergens: "has Gluten, has Eggs",
  },
  {
    name: "Hazelnut Cookie",
    price: 4.00,
    imageUrl: "/baker_shelf/Hazelnut Cookies.png",
    category: "bakery-shelf",
    description: "Buttery cookies studded with toasted hazelnuts and a hint of vanilla.",
    allergens: "has Nuts, has Gluten, has Eggs, has Dairy",
  },
  {
    name: "Sweetheart Cookie",
    price: 4.00,
    imageUrl: "/baker_shelf/Sweetheart Cookie.png",
    category: "bakery-shelf",
    description: "Heart-shaped butter cookies with a delicate sweetness.",
    allergenFree: "Nut Free",
    allergens: "has Gluten, has Eggs, has Dairy",
  },
];

const samples = raw.map((p, i) => ({
  ...p,
  id: String(i + 1),
  slug: slugify(p.name, { lower: true, strict: true }),
}));

export default samples;
